### ISSUE TITLE
bug: Importer importState.MgmDetails.IsSuperManager set to false in case of CP MDS

### ISSUE THREAD

**Issue by alf-cactus** [CactuseSecurity/firewall-orchestrator#3176]
Imported CP MDS via FWO GUI without entering domain. Auto-discovery worked perfect. When debugging importState.MgmDetails.IsSuperManager during runtime it is set to false

**Comment by tpurschke** [comment]
fixed in #3200

**Comment by alf-cactus** [comment]
I still have the issue after updating my import-rework with cactusEsecurity:importer-rework
